import fs from 'fs'
import path from 'path'
import { getRepoBySlug, getEnvironmentByName, pullEnvironment, ApiError } from '../api.js'
import { findProjectConfig } from '../config.js'
import { success, warn, error, hint, blank, header, spinner, fmt } from '../output.js'
import type { PullVariable, SkippedVariable } from '@pullenv/shared'

interface PullOptions {
  repo?: string
  env?: string
  output?: string
  force: boolean
  dryRun: boolean
}

export async function pullCommand(options: PullOptions): Promise<void> {
  // ── 1. Resolve repo + env from options or project config ───────────────────
  let repoSlug = options.repo
  let envName = options.env
  let outputFile = options.output ?? '.env.local'

  if (!repoSlug || !envName) {
    const found = findProjectConfig()
    if (found) {
      repoSlug ??= found.config.repoFullName
      envName ??= found.config.defaultEnv
      outputFile = options.output ?? found.config.outputFile
    }
  }

  if (!repoSlug) {
    error('No repo specified. Pass --repo owner/name or run pullenv init first.')
    process.exit(1)
  }
  if (!envName) {
    error('No environment specified. Pass --env <name> or run pullenv init first.')
    process.exit(1)
  }

  // ── 2. Resolve IDs ─────────────────────────────────────────────────────────
  const spin = spinner(`Resolving ${fmt.bold(repoSlug)} / ${fmt.bold(envName)}`)

  const { repoId, envId } = await resolveIds(spin, repoSlug, envName)

  // ── 3. Pull variables ──────────────────────────────────────────────────────
  spin.update(`Pulling ${fmt.bold(envName)} variables`)

  let data
  try {
    data = await pullEnvironment(repoId, envId)
  } catch (e) {
    spin.stop()
    if (e instanceof ApiError) {
      if (e.status === 403) {
        error(`Access denied: ${e.message}`)
        hint('Ask a repo admin to grant you access to this environment.')
      } else {
        error(`Pull failed: ${e.message}`)
      }
      process.exit(1)
    }
    throw e
  }

  spin.stop()

  const { variables, skipped, meta } = data

  // ── 4. Dry-run: just show what would be written ────────────────────────────
  if (options.dryRun) {
    header(`Dry run — ${meta.repoFullName} / ${meta.environment}`)
    blank()
    printVariableSummary(variables, skipped)
    blank()
    hint(`No file written (--dry-run).`)
    return
  }

  // ── 5. Safety check: don't overwrite without --force ──────────────────────
  const outputPath = path.resolve(outputFile)
  if (fs.existsSync(outputPath) && !options.force) {
    error(`${outputFile} already exists. Use --force to overwrite.`)
    process.exit(1)
  }

  // ── 6. Write the file ─────────────────────────────────────────────────────
  const lines: string[] = [
    `# Generated by pullenv — ${meta.repoFullName} / ${meta.environment}`,
    `# Pulled at: ${meta.pulledAt}`,
    `# DO NOT COMMIT this file.`,
    '',
  ]

  for (const v of variables) {
    if (v.description) {
      lines.push(`# ${v.description}`)
    }
    lines.push(`${v.key}=${formatValue(v.value)}`)
  }

  fs.writeFileSync(outputPath, lines.join('\n') + '\n', { mode: 0o600 })

  // ── 7. Ensure .gitignore covers the output file ───────────────────────────
  const wasAdded = ensureGitignored(outputFile)

  // ── 8. Output summary ─────────────────────────────────────────────────────
  blank()
  header(
    `${meta.repoFullName} / ${meta.environment}`,
    `${meta.variableCount} variables → ${outputFile}`,
  )
  blank()
  printVariableSummary(variables, skipped)
  blank()
  success(`Wrote ${meta.variableCount} variable${meta.variableCount !== 1 ? 's' : ''} to ${fmt.bold(outputFile)}`)
  if (wasAdded) hint(`Added ${outputFile} to .gitignore`)
  if (skipped.length > 0) {
    warn(`${skipped.length} variable${skipped.length !== 1 ? 's' : ''} skipped (no value set)`)
    skipped.filter((s) => s.isRequired).forEach((s) => {
      hint(`  ${fmt.red('required')} ${s.key} — ${s.reason}`)
    })
  }
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

/** Wraps values containing spaces or special shell characters in double quotes. */
function formatValue(value: string): string {
  if (/[\s"'#$`\\]/.test(value)) {
    return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`
  }
  return value
}

/**
 * Ensures the given filename is in .gitignore.
 * Returns true if a new line was appended, false if it was already there.
 */
function ensureGitignored(filename: string): boolean {
  const gitignorePath = path.resolve('.gitignore')
  try {
    const existing = fs.existsSync(gitignorePath)
      ? fs.readFileSync(gitignorePath, 'utf-8')
      : ''
    const lines = existing.split('\n').map((l) => l.trim())
    if (lines.includes(filename)) return false
    fs.appendFileSync(gitignorePath, `\n${filename}\n`)
    return true
  } catch {
    return false
  }
}

async function resolveIds(
  spin: ReturnType<typeof spinner>,
  repoSlug: string,
  envName: string,
): Promise<{ repoId: string; envId: string }> {
  try {
    const repo = await getRepoBySlug(repoSlug)
    if (!repo) {
      spin.stop()
      error(`Repo "${repoSlug}" not found in Pullenv. An admin needs to register it first.`)
      process.exit(1)
    }

    const env = await getEnvironmentByName(repo.id, envName)
    if (!env) {
      spin.stop()
      error(`Environment "${envName}" not found for ${repoSlug}.`)
      hint(`Run ${fmt.bold('pullenv envs --repo ' + repoSlug)} to see available environments.`)
      process.exit(1)
    }

    return { repoId: repo.id, envId: env.id }
  } catch (e) {
    spin.stop()
    throw e
  }
}

function printVariableSummary(variables: PullVariable[], skipped: SkippedVariable[]): void {
  for (const v of variables) {
    const source = v.version === null ? fmt.dim('(default)') : fmt.dim(`v${v.version}`)
    const req = v.isRequired ? '' : fmt.dim(' optional')
    console.log(`  ${fmt.green('✓')} ${fmt.bold(v.key)} ${source}${req}`)
  }
  for (const s of skipped) {
    const req = s.isRequired ? fmt.red(' required') : fmt.dim(' optional')
    console.log(`  ${fmt.yellow('–')} ${fmt.dim(s.key)}${req} ${fmt.dim('(skipped)')}`)
  }
}
